#!/usr/bin/env python3
"""Translate a corpus's [ui.*] points to another screen size and write them into res/<W>x<H>.toml.

    .venv/bin/python scripts/res-map.py corpora/stellaris 2560x1440          # print the mapped points
    .venv/bin/python scripts/res-map.py corpora/stellaris 2560x1440 --write  # update res/2560x1440.toml

The corpus's res/map.toml gives the scale per resolution and the anchor of each UI group (see there).
Screen templates are not mapped: capture them at the new size (scripts/play/capture-template.py).
"""

from __future__ import annotations

import argparse
import copy
import re
import sys
import tomllib
from pathlib import Path

IMAGE = (1568, 882)
ANCHORS = {"top_left": (0.0, 0.0), "center": (IMAGE[0] / 2, IMAGE[1] / 2)}


def _anchor(path: str, anchors: dict) -> tuple[float, float]:
    """Most specific anchor: `market.resources.energy` matches `market.resources`, then `market`."""
    parts = path.split(".")
    for n in range(len(parts), 0, -1):
        name = anchors.get(".".join(parts[:n]))
        if name:
            return ANCHORS[name]
    return ANCHORS[anchors.get("default", "top_left")]


def _is_point(v) -> bool:
    return isinstance(v, list) and len(v) == 2 and all(isinstance(x, int) for x in v)


def mapped_ui(corpus: Path, resolution: str) -> dict:
    """The manifest's [ui.*] with every point and listed distance translated to `resolution`."""
    corpus = Path(corpus)
    spec = tomllib.loads((corpus / "res/map.toml").read_text(encoding="utf-8"))
    scale = spec["scale"][resolution]                       # KeyError for an unmeasured resolution
    anchors = spec.get("anchors", {})
    distances = set(spec.get("distances", {}).get("keys", []))
    ui = copy.deepcopy(tomllib.loads((corpus / "manifest.toml").read_text(encoding="utf-8")).get("ui", {}))

    def walk(node: dict, prefix: str) -> None:
        for key, val in node.items():
            path = f"{prefix}.{key}" if prefix else key
            if isinstance(val, dict):
                walk(val, path)
            elif _is_point(val):
                if val != [0, 0]:                           # uncalibrated stays uncalibrated
                    ax, ay = _anchor(path, anchors)
                    node[key] = [round(ax + scale * (val[0] - ax)), round(ay + scale * (val[1] - ay))]
            elif path in distances and isinstance(val, int | float) and val:
                node[key] = round(val * scale)
    walk(ui, "")
    return ui


def _toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(v, list):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {_toml_value(x)}" for k, x in v.items()) + " }"
    return str(v)


def render_ui(ui: dict, resolution: str) -> str:
    lines = [f"# [ui.*] below: generated by scripts/res-map.py for {resolution} from manifest.toml and res/map.toml."]
    for section, table in ui.items():
        lines.append(f"\n[ui.{section}]")
        for key, val in table.items():
            lines.append(f"{key} = {_toml_value(val)}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("corpus")
    ap.add_argument("resolution")
    ap.add_argument("--write", action="store_true", help="replace the [ui.*] part of res/<resolution>.toml")
    a = ap.parse_args(argv)
    text = render_ui(mapped_ui(Path(a.corpus), a.resolution), a.resolution)
    if not a.write:
        print(text)
        return 0
    out = Path(a.corpus) / "res" / f"{a.resolution}.toml"
    old = out.read_text(encoding="utf-8") if out.exists() else ""
    # keep everything before the first [ui.*] table (the measured screens), replace the rest
    head = re.split(r"(?m)^(?:# \[ui\.\*\] below.*\n\s*)?\[ui\.", old, maxsplit=1)[0].rstrip() + "\n\n"
    out.write_text(head + text, encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
